# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


[[override]]
  name = "golang.org/x/crypto"
  revision = "614d502a4dac94afa3a6ce146bd1736da82514c6"

[[override]]
  name = "github.com/prometheus/client_model"
  revision = "99fa1f4be8e564e8a6b613da7fa6f46c9edafc6c"

[[override]]
  # Because of the lnd specify strict revision of genproto we also need to do
  # that, otherwise we met dep error.
  name = "google.golang.org/genproto"
  revision = "df60624c1e9b9d2973e889c7a1cff73155da81c4"

[[constraint]]
  name = "github.com/btcsuite/btcd"
  revision = "79e00513b1011888b1e675157ab89f527f901cae"

[[constraint]]
  name = "github.com/golang/protobuf"
  revision = "bbd03ef6da3a115852eaf24c8a1c46aeb39aa175"

[[constraint]]
  name = "github.com/jessevdk/go-flags"
  version = "1.4.0"

[[constraint]]
  # Use bitlum source for lnd as a temporary fork till pull requests will be
  # merged
  name = "github.com/lightningnetwork/lnd"
  source = "github.com/bitlum/lnd"
  revision = "b07499f227bd78dbceaa8c6ee047f1c033716cdf"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.8.0"

[[constraint]]
  name = "golang.org/x/net"
  revision = "ae89d30ce0c63142b652837da33d782e2b0a9b25"

[[constraint]]
  name = "google.golang.org/grpc"
  revision = "8dea3dc473e90c8179e519d91302d0597c0ca1d1"

[[constraint]]
  name = "gopkg.in/macaroon.v2"
  revision = "bed2a428da6e56d950bed5b41fcbae3141e5b0d0"

[[constraint]]
  name = "github.com/jinzhu/gorm"
  version = "1.9.1"

[[constraint]]
  name = "github.com/montanaflynn/stats"
  version = "0.3.0"


[prune]
  go-tests = true
  unused-packages = true