version: "3.5"

# Explicitly defined connector network to be able to set static IPs
networks:
  connector.simnet:
    name: connector.simnet
    driver: bridge
    ipam:
      config:
      - subnet: 172.100.0.0/24



# Default settings for all containers.
x-defaults:
  &defaults

  # Using automatically assigned ip address from connect.simnet network.
  networks:
    connector.simnet:

  # Using syslog driver and set tag to container_name.
  logging:
    driver: syslog
    options:
      tag: "connector-docker/{{ .Name }}"

  # Restart on exit.
  restart: always

services:
  hub.simnet:
    << : *defaults
    container_name: hub.simnet
    image: hub.simnet
    build:
      context: ./hub/
      args:
        - HUB_REVISION
    restart: always
    volumes:
      - "db:/db"
      # This directory should exist on host, so connector should be deployed
      # first, with lightning network daemon.
      - /connector/bitcoin-lightning.simnet.primary:/root/.lnd/:ro
    ports:
      # GraphQL endpoint
      - "3000:3000"

      # Prometheus monitoring
      - "19999:19999"

volumes:
  db: