version: "3.5"

# Explicitly defined connector network to be able to set static IPs
networks:
  connector.testnet:
    name: connector.testnet
    driver: bridge
    ipam:
      config:
      - subnet: 172.100.1.0/24

# Default settings for all containers.
x-defaults:
  &defaults

  # Using automatically assigned ip address from connect.testnet network.
  networks:
    connector.testnet:

  # Using syslog driver and set tag to container_name.
  logging:
    driver: syslog
    options:
      tag: "connector-docker/{{ .Name }}"

  # Restart on exit.
  restart: always

services:
  hub.testnet:
    << : *defaults
    container_name: hub.testnet
    image: hub.testnet
    build:
      context: ./hub/
      args:
        - HUB_REVISION
    restart: always
    volumes:
      - "db:/db"
      # This directory should exist on host, so connector should be deployed
      # first, with lightning network daemon.
      - /connector/bitcoin-lightning.testnet:/root/.lnd/:ro
    ports:
      # GraphQL endpoint
      - "80:3000"

      # Prometheus monitoring
      - "19999:19999"

  hubcli:
    build: hubcli
    image: bitlum/hubcli
    container_name: hubcli
    restart: always
    volumes:
      - "db:/db"
      # This directory should exist on host, so connector should be deployed
      # first, with lightning network daemon.
      - /connector/bitcoin-lightning.testnet:/root/.lnd/:ro

volumes:
  db: