version: "3.5"


# Define network compatible with payserver network
networks:
  connector.simnet:
    name: connector.simnet
    driver: bridge
    ipam:
      config:
      - subnet: 172.100.1.0/24

# Default settings for all containers.
x-defaults:
  &defaults

  logging:
    driver: "json-file"
    options:
        max-size: "200m"
        max-file: "10"

# Using automatically assigned ip address from connect.simnet network.
  networks:
    connector.simnet:

  # Restart on exit.
  restart: always

services:
  hub.simnet:
    << : *defaults
    container_name: hub.simnet
    image: hub.simnet
    build:
      context: ./hub/
    volumes:
      - "db:/db"
      # This directory should exist on host, so payserver should be deployed
      # first, with lightning network daemon.
      - /connector/bitcoin-lightning.simnet.secondary:/root/.lnd/:ro
    ports:
      # GraphQL endpoint
      - "80:3000"

      # Prometheus monitoring
      - "19999:19999"

  hubcli.simnet:
    << : *defaults
    container_name: hubcli.simnet
    image: hubcli.simnet
    build: hubcli
    volumes:
      - "db:/db"
      # This directory should exist on host, so payserver should be deployed
      # first, with lightning network daemon.
      - /connector/bitcoin-lightning.simnet.secondary:/root/.lnd/:ro

volumes:
  db: